name: 3dunet
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.2
  - pytorch-3dunet
  - h5py
  - imageio
  - ipywidgets
  - ipykernel
  - matplotlib
  - numpy
  - pillow
  - pyyaml
  - scikit-image 
  - scipy
  - tqdm
  - yaml

