# Download test data from: https://osf.io/8jz7e/
model_path: /Users/w.zhao/Projects/MemSeg/240408_train2/best_checkpoint.pytorch
model:
  name: UNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 1
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcr
  # initial number of feature maps
  f_maps: 16
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
predictor:
  name: 'StandardPredictor'
loaders:
  # save predictions to output_dir
  output_dir: /Users/w.zhao/Projects/MemSeg/Results/Test
  # batch dimension; if number of GPUs is N > 1, then a batch_size of N * batch_size will automatically be taken for DataParallel
  batch_size: 1
  # how many subprocesses to use for data loading
  num_workers: 8
  # test loaders configuration
  test:
    file_paths:
      - /Users/w.zhao/Projects/MemSeg/Dataset/Test

    slice_builder:
      name: SliceBuilder
      patch_shape: [64, 128, 128]
      stride_shape: [20, 80, 80]

    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true
